Umstellung auf IP basierte Outgoing Firewall.

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -31,12 +31,11 @@ case "$1" in
      [ -e "$INSTALLED" ] || exit 0
 
      . $HELPERFUNCTIONS
-     SETUPSCRIPT="/usr/share/linuxmuster-ipfire/setup.sh"
+     SETUPSCRIPT="linuxmuster-ipfire --setup --first"
 
      if ! test_pwless_fw; then
-      echo "You have to repeat package configuration with"
-      echo "# dpkg-reconfigure linuxmuster-ipfire"
-      echo "when you have fixed this!"
+      echo "You have to do first an initial setup of IPFire by inkoving"
+      echo "# $SETUPSCRIPT"
       exit 0
      fi
 
@@ -45,39 +44,63 @@ case "$1" in
 	  echo "IPFire detected!"
 	 else
 	  echo "This is not an IPFire firewall!"
-	  echo "Don't forget to invoke the setup script"
-	  echo "$SETUPSCRIPT"
-	  echo "later when IPFire is installed!"
-	  exit 0
+	  exit 1
 	 fi
-
+ 
      # update linuxmuster.net scripts on IPFire
-     if exec_ipcop /bin/ls /var/linuxmuster; then
-      echo -n "Uploading linuxmuster.net configuration scripts to IPFire ... "
-      exec_ipcop /bin/rm -rf /var/linuxmuster ; RC="$?"
-      put_ipcop /var/lib/linuxmuster-ipfire /var/linuxmuster ; [ "$?" != "0" ] && RC="$?"
+     echo -n "Uploading linuxmuster.net configuration scripts to IPFire ... "
+     exec_ipcop /bin/rm -rf /var/linuxmuster
+     put_ipcop /var/lib/linuxmuster-ipfire /var/linuxmuster ; RC="$?"
+     if [ "$RC" = "0" ]; then
+      echo "Ok!"
+     else
+      echo "Failed!"
+      exit 1
+     fi
+
+     # repair outgoing rules file if necessary
+     if ! exec_ipcop "/bin/grep \^\"ALLOW\;on\;allowedips\;\" /var/ipfire/outgoing/rules"; then
+      echo -n "Repairing outgoing rules ... "
+      exec_ipcop "/bin/sed -e \"s|@@serverip@@|$serverip|\" /var/linuxmuster/templates/outgoing/rules > /var/ipfire/outgoing/rules" ; RC="$?"
       if [ "$RC" = "0" ]; then
+       fwout_reload=yes
        echo "Ok!"
-       # repair outgoing rules file if necessary
-       if ! exec_ipcop "/bin/grep \^\"ALLOW\;on\;allowedmacs\;\" /var/ipfire/outgoing/rules"; then
-        echo -n "Repairing outgoing rules ... "
-        exec_ipcop "/bin/sed -e \"s|@@serverip@@|$serverip|\" /var/linuxmuster/templates/outgoing/rules > /var/ipfire/outgoing/rules" ; RC="$?"
-        if [ "$RC" = "0" ]; then
-         exec_ipcop /var/linuxmuster/reload_outgoing.sh
-         echo "Ok!"
-        else
-         echo "Failed!"
-        fi
-       fi
       else
        echo "Failed!"
+       exit 1
       fi
-     else
-	  echo "IPFire is not yet configured!"
-	  echo "You have to invoke the setup script"
-	  echo "$SETUPSCRIPT"
-	  echo "to prepare IPFire for use with linuxmuster.net!"
      fi
+
+     # convert macs to ips for ip based external firewall
+     searchstr="$(head -1 $BLOCKEDHOSTSINTERNET)"
+     if validmac "$searchstr"; then
+      echo "Converting blocked mac addresses to ips because external firewall has changed."
+      macs="$(cat $BLOCKEDHOSTSINTERNET)"
+      rm $BLOCKEDHOSTSINTERNET
+      touch $BLOCKEDHOSTSINTERNET
+      for i in $macs; do
+       if validip "$i"; then
+        echo "$i" >> $BLOCKEDHOSTSINTERNET
+       else
+        get_ip "$i"
+        echo "$RET" >> $BLOCKEDHOSTSINTERNET
+       fi
+      done
+      fwext_reload=yes
+      fwout_reload=""
+     fi
+     
+     # test for obsolete allowedmacs file
+     if [ -e "$CACHEDIR/allowedmacs" ]; then
+      rm -f "$CACHEDIR/allowedmacs"
+      fwext_reload=yes
+      fwout_reload=""
+     fi
+
+     # reload firewall     
+     [ -n "$fwout_reload" ] && exec_ipcop /var/linuxmuster/reload_outgoing.sh
+     [ -n "$fwext_reload" ] && $SCRIPTSDIR/internet_on_off.sh
+
 
      ;;
 
