* Skripte für Einstellungs-Backup und -Restore hinzugefügt. * Wrapper-Skript /usr/sbin/linuxmuster-ipfire hinzugefügt, das   entprechend dem Kommandozeilenparameter die Skripte backup.sh,   restore.sh und setup.sh in usr/share/linuxmuster-ipfire einliest   (siehe linuxmuster-ipfire --help).

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -25,69 +25,69 @@ set -e
 case "$1" in
     configure)
 
-	[ -e /usr/share/linuxmuster/config/dist.conf ] && . /usr/share/linuxmuster/config/dist.conf
+	 [ -e /usr/share/linuxmuster/config/dist.conf ] && . /usr/share/linuxmuster/config/dist.conf
 
-	# do nothing if linuxmuster.net ist not yet installed
-        [ -e "$INSTALLED" ] || exit 0
+	 # do nothing if linuxmuster.net ist not yet installed
+     [ -e "$INSTALLED" ] || exit 0
 
-        . $HELPERFUNCTIONS
-        SETUPSCRIPT="/usr/share/linuxmuster-ipfire/setup.sh"
+     . $HELPERFUNCTIONS
+     SETUPSCRIPT="/usr/share/linuxmuster-ipfire/setup.sh"
 
-        if ! test_pwless_fw; then
-         echo "You have to repeat package configuration with"
-         echo "# dpkg-reconfigure linuxmuster-ipfire"
-         echo "when you have fixed this!"
-         exit 0
-        fi
+     if ! test_pwless_fw; then
+      echo "You have to repeat package configuration with"
+      echo "# dpkg-reconfigure linuxmuster-ipfire"
+      echo "when you have fixed this!"
+      exit 0
+     fi
 
-	# test if firewall is IPFire
-	if exec_ipcop /bin/ls /var/ipfire; then
-	 echo "IPFire detected!"
-	else
-	 echo "This is not an IPFire firewall!"
-	 echo "Don't forget to invoke the setup script"
-	 echo "$SETUPSCRIPT"
-	 echo "later when IPFire is installed!"
-	 exit 0
-	fi
+	 # test if firewall is IPFire
+	 if exec_ipcop /bin/ls /var/ipfire; then
+	  echo "IPFire detected!"
+	 else
+	  echo "This is not an IPFire firewall!"
+	  echo "Don't forget to invoke the setup script"
+	  echo "$SETUPSCRIPT"
+	  echo "later when IPFire is installed!"
+	  exit 0
+	 fi
 
-        # update linuxmuster.net scripts on IPFire
-        if exec_ipcop /bin/ls /var/linuxmuster; then
-         echo -n "Uploading linuxmuster.net configuration scripts to IPFire ... "
-         exec_ipcop /bin/rm -rf /var/linuxmuster ; RC="$?"
-         put_ipcop /var/lib/linuxmuster-ipfire /var/linuxmuster ; [ "$?" != "0" ] && RC="$?"
-         if [ "$RC" = "0" ]; then
-          echo "Ok!"
-          # repair outgoing rules file if necessary
-          if ! exec_ipcop "/bin/grep \^\"ALLOW\;on\;allowedmacs\;\" /var/ipfire/outgoing/rules"; then
-           echo -n "Repairing outgoing rules ... "
-           exec_ipcop "/bin/sed -e \"s|@@serverip@@|$serverip|\" /var/linuxmuster/templates/outgoing/rules > /var/ipfire/outgoing/rules" ; RC="$?"
-           if [ "$RC" = "0" ]; then
-            exec_ipcop /var/linuxmuster/reload_outgoing.sh
-            echo "Ok!"
-           else
-            echo "Failed!"
-           fi
-          fi
-         else
-          echo "Failed!"
-         fi
+     # update linuxmuster.net scripts on IPFire
+     if exec_ipcop /bin/ls /var/linuxmuster; then
+      echo -n "Uploading linuxmuster.net configuration scripts to IPFire ... "
+      exec_ipcop /bin/rm -rf /var/linuxmuster ; RC="$?"
+      put_ipcop /var/lib/linuxmuster-ipfire /var/linuxmuster ; [ "$?" != "0" ] && RC="$?"
+      if [ "$RC" = "0" ]; then
+       echo "Ok!"
+       # repair outgoing rules file if necessary
+       if ! exec_ipcop "/bin/grep \^\"ALLOW\;on\;allowedmacs\;\" /var/ipfire/outgoing/rules"; then
+        echo -n "Repairing outgoing rules ... "
+        exec_ipcop "/bin/sed -e \"s|@@serverip@@|$serverip|\" /var/linuxmuster/templates/outgoing/rules > /var/ipfire/outgoing/rules" ; RC="$?"
+        if [ "$RC" = "0" ]; then
+         exec_ipcop /var/linuxmuster/reload_outgoing.sh
+         echo "Ok!"
         else
-	 echo "IPFire is not yet configured!"
-	 echo "You have to invoke the setup script"
-	 echo "$SETUPSCRIPT"
-	 echo "to prepare IPFire for use with linuxmuster.net!"
+         echo "Failed!"
         fi
+       fi
+      else
+       echo "Failed!"
+      fi
+     else
+	  echo "IPFire is not yet configured!"
+	  echo "You have to invoke the setup script"
+	  echo "$SETUPSCRIPT"
+	  echo "to prepare IPFire for use with linuxmuster.net!"
+     fi
 
-        ;;
+     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
-	;;
+	 ;;
 
     *)
-        echo "postinst called with unknown argument \`$1'" >&2
-        exit 1
-    ;;
+     echo "postinst called with unknown argument \`$1'" >&2
+     exit 1
+     ;;
 esac
 
 # dh_installdeb will replace this with shell code automatically
